#url path to running veraPDF-rest
#pridani custom properties to .yml
#https://stackoverflow.com/questions/49771099/how-to-get-string-from-config-yml-file-in-dropwizard-resource
#https://www.dropwizard.io/en/latest/manual/core.html#configuration
urlToVeraPDFrest: http://pdfa.k.utb.cz:7070/api/validate/auto
# na windows musí být cesta config\\RuleViolationException.json
# na linuxu musí být cesta config/RuleViolationException.json
pathToRuleViolationExceptionFile: RuleViolationException.json

pathToSentFilesFolder: logs/files/

logging:
  level: INFO
  loggers:
    dropwizard: DEBUG
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
stagpdfa:
  exceptions:
    - 6.1.2
    - 6.3.2
    - 6.1.7
    - 6.2.2
  pathToSentFilesFolder: logs/files/
  urlToVeraPDFrest: http://pdfa.k.utb.cz:7070/api/validate/auto
